config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :vehicles
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicle.rb
# frozen_string_literal: true

class Vehicle < ApplicationRecord
  # BEGIN
  has_one_attached :image
  # END

  validates :manufacture, presence: true
  validates :model, presence: true
  validates :color, presence: true
  validates :doors, presence: true, numericality: { only_integer: true }
  validates :kilometrage, presence: true, numericality: { only_integer: true }
  validates :production_year, presence: true

  # BEGIN
  validates :image, attached: true, content_type: %i[png jpg jpeg], size: { less_than: 5.megabytes }
  # END
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/vehicles_controller.rb
# frozen_string_literal: true

class VehiclesController < ApplicationController
  def index
    @vehicles = Vehicle.all
  end

  def show
    @vehicle = Vehicle.find params[:id]
  end

  def new
    @vehicle = Vehicle.new
  end

  def edit
    @vehicle = Vehicle.find params[:id]
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)

    if @vehicle.save
      redirect_to @vehicle, notice: 'Vehicle was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @vehicle = Vehicle.find params[:id]

    if @vehicle.update(vehicle_params)
      redirect_to @vehicle, notice: 'Vehicle was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @vehicle = Vehicle.find params[:id]

    @vehicle.destroy

    redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.'
  end

  private

  # Only allow a list of trusted parameters through.
  def vehicle_params
    params.require(:vehicle).permit(
      :manufacture,
      :model,
      :color,
      :doors,
      :kilometrage,
      :production_year,
      :image
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.slim
= content_for :title do
  = t('.title')

app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    title = t('.title')
    == csrf_meta_tags
    == csp_meta_tag
    meta name="keywords" content="template language"
    meta name="author" content='author'
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'

  body.d-flex.flex-column.h-100

    = render 'layouts/shared/nav'

    = render 'layouts/shared/flash'

    main
      .mt-4.mb-5.pb-5
        .container
          .p-4.align-items-center.border.shadow.bg-white.rounded-3
            .mb-4
              h2 = yield :title

            == yield

    footer.bg-dark.text-light.mt-auto
      .container-xl
        .row.py-2
          = t('.hexlet_title', year: Time.current.year)

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |_type, msg|
      .alert.alert-info
        = msg

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light
      a.navbar-brand.me-md-4(href='/')
        = image_tag asset_pack_path('media/images/logo.png'), width: 30, alt: t('.hexlet_logo')

      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav
          li.nav-item.me-2
            = link_to t('.home'), root_path, class: 'nav-link link-dark'
          li.nav-item.me-2
            = link_to t('.vehicles'), vehicles_path, class: 'nav-link link-dark'

app/views/vehicles/_form.html.slim
= simple_form_for(@vehicle) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :manufacture
  = f.input :model
  = f.input :color
  = f.input :doors
  = f.input :kilometrage
  = f.input :production_year, discard_day: true, discard_month: true

  hr

  - if @vehicle.image_attachment
    = image_tag @vehicle.image.variant(resize_to_limit: [200, 100]), class: 'img-thumbnail mb-2'
  / BEGIN
  = f.input :image, as: :file
  / END
  = f.button :submit, class: 'btn btn-success mt-4 btn-block'

app/views/vehicles/edit.html.slim
= content_for :title do
  = t('.title')

== render 'form'

hr

.d-flex
  = link_to t('show'), @vehicle, class: 'btn btn-outline-primary me-2'
  = link_to t('back'), :back, class: 'btn btn-outline-primary'

app/views/vehicles/index.html.slim
= content_for :title do
  = t('.title')

= link_to t('.new_vehicle'), new_vehicle_path, class: 'btn btn-primary my-2'

table.table.table-striped.table-hover.mb-5
  thead
    tr
      th{ scope: :col } #
      th{ scope: :col } = t('.manufacture')
      th{ scope: :col } = t('.model')
      th{ scope: :col } = t('.color')
      th{ scope: :col } = t('.doors')
      th{ scope: :col } = t('.kilometrage')
      th{ scope: :col } = t('.production_year')
      th{ scope: :col } = t('.preview')
      th

  tbody
    - @vehicles.each_with_index do |vehicle, i|
      tr
        th{ scope: :col } = i + 1
        td = vehicle.manufacture
        td = vehicle.model
        td = vehicle.color
        td = vehicle.doors
        td = vehicle.kilometrage
        td = vehicle.production_year
        td
          - if vehicle.image_attachment
            = image_tag vehicle.image.variant(resize_to_limit: [200, 100]), class: 'img-thumbnail'
        td.d-flex
          = link_to t('show'), vehicle, class: 'me-4'
          = link_to t('edit'), edit_vehicle_path(vehicle), class: 'me-4'
          = link_to t('destroy'), vehicle, data: { confirm: t('destroy_confirmation') }, method: :delete

= link_to t('.new_vehicle'), new_vehicle_path, class: 'btn btn-primary'

app/views/vehicles/new.html.slim
= content_for :title do
  = t('.title')

== render 'form'

hr

= link_to t('back'), :back, class: 'btn btn-outline-primary'

app/views/vehicles/show.html.slim
= content_for :title do
  = @vehicle.model

.row
  .col-6
    p
      strong.me-2 = t('.manufacture')
      = @vehicle.manufacture
    p
      strong.me-2 = t('.color')
      = @vehicle.color
    p
      strong.me-2 = t('.doors')
      = @vehicle.doors
    p
      strong.me-2 = t('.kilometrage')
      = @vehicle.kilometrage
    p
      strong.me-2 = t('.production_year')
      = @vehicle.production_year
  .col-6
    - if @vehicle.image_attachment
      = image_tag(@vehicle.image, class: 'img-fluid')

hr

.d-flex
  = link_to t('edit'), edit_vehicle_path(@vehicle), class: 'btn btn-outline-primary me-2'
  = link_to t('back'), :back, class: 'btn btn-outline-primary'